### ISSUE TITLE
[BUG] ts0601_trv_siterwell.py custom quirk now fails to load.

### ISSUE THREAD

**Issue by accessiblepixel** [zigpy/zha-device-handlers#2647]
### Bug description

After updating from an older home assistant to latest home assistant, the quirk wouldn't run and trying to find an updated ts0601_trv_siterwell.py file from the thread (from Jan 3rd), it gives the following error.

Now I could just be being a donut and getting something wrong here (quite possible!) but it would be very appreciated if someone could point me in the right direction (or if it is indeed a bug a potential fix or workaround)?

The temperature still reports and updates, but all the other sensors in the valve are now greyed out.

Thank you muchly.

### Steps to reproduce

Install quirk, fails to load with exception "Unexpected exception importing custom quirk 'ts0601_trv_siterwell'"

### Expected behavior

It to load the quirk.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=0, maximum_buffer_size=82, maximum_incoming_transfer_size=255, server_mask=11264, maximum_outgoing_transfer_size=255, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0301",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0201",
        "0x0204",
        "0xef00"
      ],
      "output_clusters": [
        "0x0003",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TYST11_czk78ptr",
  "model": "zk78ptr",
  "class": "zhaquirks.tuya.ts0601_trv.SiterwellGS361_Type1"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.10.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.45",
    "supervisor": "2023.10.0",
    "host_os": "Home Assistant OS 10.5",
    "docker_version": "23.0.6",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "circadian_lighting": {
      "version": "2.1.4",
      "requirements": []
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "additional_ca": {
      "version": "0.1.0",
      "requirements": []
    },
    "frigate": {
      "version": "4.0.0",
      "requirements": [
        "pytz==2022.7"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "after_dependencies": [
      "onboarding",
      "usb"
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "config_flow": true,
    "dependencies": [
      "file_upload"
    ],
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp",
      "universal_silabs_flasher"
    ],
    "requirements": [
      "bellows==0.36.5",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.104",
      "zigpy-deconz==0.21.1",
      "zigpy==0.57.2",
      "zigpy-xbee==0.18.3",
      "zigpy-zigate==0.11.0",
      "zigpy-znp==0.11.5",
      "universal-silabs-flasher==0.0.14",
      "pyserial-asyncio-fast==0.11"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_uzg-01._tcp.local.",
        "name": "uzg-01*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 50479,
    "manufacturer": "_TYST11_czk78ptr",
    "model": "zk78ptr",
    "name": "_TYST11_czk78ptr zk78ptr",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.tuya.ts0601_trv.SiterwellGS361_Type1",
    "manufacturer_code": 0,
    "power_source": "Battery or Unknown",
    "lqi": 81,
    "rssi": null,
    "last_seen": "2023-10-12T20:52:50",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=0, maximum_buffer_size=82, maximum_incoming_transfer_size=255, server_mask=11264, maximum_outgoing_transfer_size=255, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0301",
          "input_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0201",
            "0x0204",
            "0xef00"
          ],
          "output_clusters": [
            "0x0003",
            "0x0019"
          ]
        }
      },
      "manufacturer": "_TYST11_czk78ptr",
      "model": "zk78ptr"
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "button.bedroom_radiator_identifybutton",
        "name": "_TYST11_czk78ptr zk78ptr"
      },
      {
        "entity_id": "climate.bedroom_radiator_thermostat",
        "name": "_TYST11_czk78ptr zk78ptr"
      },
      {
        "entity_id": "sensor.bedroom_radiator_battery",
        "name": "_TYST11_czk78ptr zk78ptr"
      },
      {
        "entity_id": "sensor.bedroom_radiator_rssi",
        "name": "_TYST11_czk78ptr zk78ptr"
      },
      {
        "entity_id": "sensor.bedroom_radiator_lqi",
        "name": "_TYST11_czk78ptr zk78ptr"
      },
      {
        "entity_id": "sensor.bedroom_radiator_hvac_action",
        "name": "_TYST11_czk78ptr zk78ptr"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "THERMOSTAT"
      }
    ],
    "user_given_name": "Bedroom Radiator",
    "device_reg_id": "69734c3c5350c8f479be86b00b9b1242",
    "area_id": "bedroom",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "THERMOSTAT",
          "id": 769
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0001": {
                "attribute_name": "app_version",
                "value": 73
              },
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "_TYST11_czk78ptr"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "zk78ptr"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xef00": {
            "endpoint_attribute": "tuya_manufacturer",
            "attributes": {
              "0x0107": {
                "attribute_name": "child_lock",
                "value": 0
              },
              "0x0404": {
                "attribute_name": "mode",
                "value": 2
              },
              "0x0202": {
                "attribute_name": "target_temperature",
                "value": 135
              },
              "0x0203": {
                "attribute_name": "temperature",
                "value": 176
              },
              "0x0112": {
                "attribute_name": "window_detection",
                "value": 1
              }
            },
            "unsupported_attributes": {}
          },
          "0x0201": {
            "endpoint_attribute": "thermostat",
            "attributes": {
              "0x001b": {
                "attribute_name": "ctrl_sequence_of_oper",
                "value": 2
              },
              "0x0000": {
                "attribute_name": "local_temperature",
                "value": 1760
              },
              "0x0002": {
                "attribute_name": "occupancy",
                "value": 1
              },
              "0x0012": {
                "attribute_name": "occupied_heating_setpoint",
                "value": 1350
              },
              "0x0025": {
                "attribute_name": "programing_oper_mode",
                "value": 0
              },
              "0x001e": {
                "attribute_name": "running_mode",
                "value": 4
              },
              "0x0029": {
                "attribute_name": "running_state",
                "value": 1
              },
              "0x001c": {
                "attribute_name": "system_mode",
                "value": 4
              },
              "0x0014": {
                "attribute_name": "unoccupied_heating_setpoint",
                "value": 1650
              }
            },
            "unsupported_attributes": {}
          },
          "0x0204": {
            "endpoint_attribute": "thermostat_ui",
            "attributes": {
              "0x0001": {
                "attribute_name": "keypad_lockout",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0033": {
                "attribute_name": "battery_quantity",
                "value": 2
              },
              "0x0034": {
                "attribute_name": "battery_rated_voltage",
                "value": 15
              },
              "0x0031": {
                "attribute_name": "battery_size",
                "value": 3
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

### Logs

<details><summary>Logs</summary>

```python
  File "/usr/local/lib/python3.11/site-packages/zhaquirks/__init__.py", line 460, in setup
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_zha_quirks/ts0601_trv_siterwell.py", line 61, in <module>
    class SiterwellManufCluster(TuyaManufClusterAttributes):
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 167, in __init_subclass__
    raise TypeError(f"Duplicate definitions exist for {duplicates}")
TypeError: Duplicate definitions exist for ['window_alarm']
```

</details>

### Additional information

Thank you :)

**Comment by javicalle** [comment]
Have you tried to remove the quirk file and test the device?

**Comment by MattWestb** [comment]
ZHA / ziggpy have make some internal changes and the quirk need being updated.
The father for tuya TRVs have posting updated working ones here https://github.com/jacekk015/zha_quirks.

**Comment by accessiblepixel** [comment]
@MattWestb Ah, thank you. I hadn't seen that your comment had been modified since you wrote it.

I first tried downloading the new quirk from the github you linked and at first I got...

```Unexpected exception importing custom quirk 'ts0601_trv_siterwell'

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zhaquirks/__init__.py", line 460, in setup
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_zha_quirks/ts0601_trv_siterwell.py", line 95
    <title>zha_quirks/ts0601_trv_siterwell.py at main · jacekk015/zha_quirks · GitHub</title>
                                                      ^
SyntaxError: invalid character '·' (U+00B7)
```
But then I realised it was a PEBKAC (problem exists between keyboard and chair) since I wget'ed the page showing the code, rather than using the github raw link to download the actual file. G'oh!

Anyway, this new version is working for me now and I can finally start valve calibration remotely - a couple of my thermostats are in awkward places so after battery replacements it can be difficult to start a valve calibration once they're back on the radiator.

Thanks to all involved for the help with this, it is much appreciated! Will these updated quirks be included in the mainline quirks at any point, so we don't have to load them as custom ones?

**Comment by MattWestb** [comment]
Its complaning on the string: 
`<title>zha_quirks/ts0601_trv_siterwell.py at main · jacekk015/zha_quirks · GitHub</title>`
That shall not being in the quirk file so likely you have downloaded the HTTP code and not the quirk code (easy to do i have doing it some times), 
Use "RAW" mode and copy the text and putting it in your quirk file or download the repro as zip and copy the file you need and it shall working OK.

**Comment by accessiblepixel** [comment]
@MattWestb 
Yes, I'd realised I'd done that, and wrote it later on in my last message, since apparently my brain was absent minded ;) We're all good now! <3

Are jacekk015's quirks ever going to be mainlined into the "main" quirks database for ZHA? Sorry if I don't know the right terminology - I wish I knew more of this stuff other than my clumsy bludgeoning to help more than reporting bugs, but here we are!

Hope life is treating you well, my friend.

**Comment by MattWestb** [comment]
Great you was getting it  working then the "winter is coming" (GTO) and it needed for all of us !!
@jacekk015 and i was doing one try for nearly 2 years ago but was fling getting it thru so both have giving it up and we trying have support on his github that is very good but the best shall being that the maintainer is helping getting it in the ZHA for alls best.

**Comment by accessiblepixel** [comment]
Reporting back after a couple of months (kinda forgot to come back and close this!).

@MattWestb  Using @jacekk015 's quirks from https://github.com/jacekk015/zha_quirks have worked perfectly fine since you pointed me in that direction, even when updating today to HA 12.05. 

Thanks @jacekk015 for working on them :)

Hope you both had a great new year. All the best.
