### ISSUE TITLE
[BUG] Integration Heiman HS1SA-E smoke detector

### ISSUE THREAD

**Issue by jochenruben** [zigpy/zha-device-handlers#2700]
### Bug description

Hi,
I integrated the device with ZHA successfully but there are no entities, no battery status etc.
The Sonoff 3.0 Stick is flashed via Python with the newest Firmware. 

Here ist the relevant log:

Logger: homeassistant
Source: components/zha/core/cluster_handlers/__init__.py:75
First occurred: 11:53:37 (15 occurrences)
Last logged: 16:36:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 64, in wrap_zigpy_exceptions
    yield
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 84, in wrapper
    return await RETRYABLE_REQUEST_DECORATOR(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/util.py", line 132, in retry
    return await func()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 377, in request
    return await self._endpoint.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/endpoint.py", line 253, in request
    return await self.device.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 293, in request
    await self._application.request(
  File "/usr/local/lib/python3.11/site-packages/zigpy/application.py", line 828, in request
    await self.send_packet(
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 1202, in send_packet
    raise DeliveryError(
zigpy.exceptions.DeliveryError: Request failed after 5 attempts: <Status.MAC_NO_ACK: 233>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 640, in async_device_initialized
    await self._async_device_joined(zha_device)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 656, in _async_device_joined
    await zha_device.async_configure()
  File "/usr/src/homeassistant/homeassistant/components/zha/core/device.py", line 578, in async_configure
    await self.identify_ch.trigger_effect(
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 83, in wrapper
    with wrap_zigpy_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 75, in wrap_zigpy_exceptions
    raise HomeAssistantError(message) from exc
homeassistant.exceptions.HomeAssistantError: Failed to send request: Request failed after 5 attempts: <Status.MAC_NO_ACK: 233>

### Steps to reproduce

Reinstalled and reconfigured - always the same problem

### Expected behavior

See min two entities

### Screenshots/Video

<details><summary>Screenshots/Video</summary>
![image](https://github.com/zigpy/zha-device-handlers/assets/131450294/c428c482-f9ed-4ccf-8337-eb2f0ad79a47)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by jochenruben** [comment]
![Screenshot 2023-11-02 164746](https://github.com/zigpy/zha-device-handlers/assets/131450294/28e1db07-5d46-4f91-b363-d0b99e5758ba)
