### ISSUE TITLE
N-ZDMS01-2 Avatto strange behavior 

### ISSUE THREAD

**Issue by Henrik1986** [zigpy/zha-device-handlers#2908]
### Problem description

The dimmer works fine when I pushes the switches on the wall. Then I do this the switches i UI (HA) goes to on/off and brightness changes. But when I turn the bulbs off they can go back to ON by itself, but only in the UI. The bulbs don't turn on - so it only shows as ON in the UI.  

### Solution description

The switches in the UI should not go to ON by itself.  

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[
![Skärmavbild 2024-01-14 kl  10 53 24](https://github.com/zigpy/zha-device-handlers/assets/20314871/30a1b57b-ea40-4e59-82b8-a8fdd9324ee0)

![Screenshot_20240118-063810](https://github.com/zigpy/zha-device-handlers/assets/20314871/2143959b-4d29-4344-876c-3b1a19a02ef2)

]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0101",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": "0x0104",
      "device_type": "0x0101",
      "input_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0xef00"
      ],
      "output_clusters": []
    },
    "242": {
      "profile_id": "0xa1e0",
      "device_type": "0x0061",
      "input_clusters": [],
      "output_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZ3210_3mpwqzuu",
  "model": "TS110E",
  "class": "zigpy.device.Device"
}]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[
[zha-b32e3c46ef098fb5042c7de854eb9c09-_TZ3210_3mpwqzuu TS110E-d8c537e70086b9a3c5b7929f0115d501.json (1).txt](https://github.com/zigpy/zha-device-handlers/files/13930979/zha-b32e3c46ef098fb5042c7de854eb9c09-_TZ3210_3mpwqzuu.TS110E-d8c537e70086b9a3c5b7929f0115d501.json.1.txt)
]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[2024-01-13 15:12:54.935 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 64, in wrap_zigpy_exceptions
    yield
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 84, in wrapper
    return await RETRYABLE_REQUEST_DECORATOR(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/util.py", line 137, in retry
    return await func()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 377, in request
    return await self._endpoint.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/endpoint.py", line 253, in request
    return await self.device.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 322, in request
    await send_request
  File "/usr/local/lib/python3.11/site-packages/zigpy/application.py", line 833, in request
    await self.send_packet(
  File "/usr/local/lib/python3.11/site-packages/bellows/zigbee/application.py", line 931, in send_packet
    raise zigpy.exceptions.DeliveryError(
zigpy.exceptions.DeliveryError: Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/core/device.py", line 585, in async_configure
    await self.identify_ch.trigger_effect(
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 83, in wrapper
    with wrap_zigpy_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 75, in wrap_zigpy_exceptions
    raise HomeAssistantError(message) from exc
homeassistant.exceptions.HomeAssistantError: Failed to send request: Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

### Additional information

In one of the pictures can you see how the switch goes on by itself. Today i use a automation to turn it off. Therefore it goes of. Otherwise it would stay on.

**Comment by Henrik1986** [comment]
Why Tuya? 
The devices is Zigbee that is connected direct to ZHA.
