### ISSUE TITLE
[Device Support Request] VALLHORN Wireless Motion Sensor

### ISSUE THREAD

**Issue by fzakfeld** [zigpy/zha-device-handlers#3165]
### Problem description

Sensor is either stuck at "Configuring" (in Home Assistant) or - when configured - won't report any state (just shows the state from when it was added). Binding to a light surprisingly works, just doesn't report any actual state to HA.

### Solution description

Fix support for VALLHORN motion sensors.

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0850",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0x0b05",
        "0x1000",
        "0xfc7c",
        "0xfc81"
      ],
      "output_clusters": [
        "0x0003",
        "0x0004",
        "0x0006",
        "0x0019",
        "0x1000"
      ]
    },
    "2": {
      "profile_id": "0x0104",
      "device_type": "0x0107",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0406"
      ],
      "output_clusters": [
        "0x0003"
      ]
    },
    "3": {
      "profile_id": "0x0104",
      "device_type": "0x0106",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0400"
      ],
      "output_clusters": [
        "0x0003"
      ]
    }
  },
  "manufacturer": "IKEA of Sweden",
  "model": "VALLHORN Wireless Motion Sensor",
  "class": "zigpy.device.Device"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.5.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.63-haos-raspi",
    "supervisor": "2024.05.1",
    "host_os": "Home Assistant OS 11.3",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {},
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "after_dependencies": [
      "onboarding",
      "usb"
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly",
      "@TheJulianJES"
    ],
    "config_flow": true,
    "dependencies": [
      "file_upload"
    ],
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp",
      "universal_silabs_flasher"
    ],
    "requirements": [
      "bellows==0.38.4",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.115",
      "zigpy-deconz==0.23.1",
      "zigpy==0.64.0",
      "zigpy-xbee==0.20.1",
      "zigpy-zigate==0.12.0",
      "zigpy-znp==0.12.1",
      "universal-silabs-flasher==0.0.18",
      "pyserial-asyncio-fast==0.11"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*slzb-07*",
        "known_devices": [
          "smlight slzb-07"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*conbee*",
        "known_devices": [
          "Conbee III"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_uzg-01._tcp.local.",
        "name": "uzg-01*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 6762,
    "manufacturer": "IKEA of Sweden",
    "model": "VALLHORN Wireless Motion Sensor",
    "name": "IKEA of Sweden VALLHORN Wireless Motion Sensor",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "quirk_id": null,
    "manufacturer_code": 4476,
    "power_source": "Battery or Unknown",
    "lqi": null,
    "rssi": null,
    "last_seen": "2024-05-22T23:32:51",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0850",
          "input_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0020",
            "0x0b05",
            "0x1000",
            "0xfc7c",
            "0xfc81"
          ],
          "output_clusters": [
            "0x0003",
            "0x0004",
            "0x0006",
            "0x0019",
            "0x1000"
          ]
        },
        "2": {
          "profile_id": "0x0104",
          "device_type": "0x0107",
          "input_clusters": [
            "0x0000",
            "0x0003",
            "0x0406"
          ],
          "output_clusters": [
            "0x0003"
          ]
        },
        "3": {
          "profile_id": "0x0104",
          "device_type": "0x0106",
          "input_clusters": [
            "0x0000",
            "0x0003",
            "0x0400"
          ],
          "output_clusters": [
            "0x0003"
          ]
        }
      },
      "manufacturer": "IKEA of Sweden",
      "model": "VALLHORN Wireless Motion Sensor"
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "binary_sensor.hallway_motion_sensor_opening",
        "name": "IKEA of Sweden VALLHORN Wireless Motion Sensor"
      },
      {
        "entity_id": "binary_sensor.hallway_motion_sensor_occupancy",
        "name": "IKEA of Sweden VALLHORN Wireless Motion Sensor"
      },
      {
        "entity_id": "button.hallway_motion_sensor_identify",
        "name": "IKEA of Sweden VALLHORN Wireless Motion Sensor"
      },
      {
        "entity_id": "sensor.hallway_motion_sensor_battery",
        "name": "IKEA of Sweden VALLHORN Wireless Motion Sensor"
      },
      {
        "entity_id": "sensor.hallway_motion_sensor_illuminance",
        "name": "IKEA of Sweden VALLHORN Wireless Motion Sensor"
      },
      {
        "entity_id": "update.hallway_motion_sensor_firmware",
        "name": "IKEA of Sweden VALLHORN Wireless Motion Sensor"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "ON_OFF_SENSOR"
      },
      {
        "name": "OCCUPANCY_SENSOR"
      },
      {
        "name": "LIGHT_SENSOR"
      }
    ],
    "user_given_name": "Hallway Motion Sensor",
    "device_reg_id": "f448cd04eabc8dcf8cdc9f4e6a562ef8",
    "area_id": "hallway",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "ON_OFF_SENSOR",
          "id": 2128
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "IKEA of Sweden"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "VALLHORN Wireless Motion Sensor"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 162
              },
              "0x0033": {
                "attribute_name": "battery_quantity",
                "value": 2
              },
              "0x0031": {
                "attribute_name": "battery_size",
                "value": 4
              },
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 26
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0020": {
            "endpoint_attribute": "poll_control",
            "attributes": {
              "0x0000": {
                "attribute_name": "checkin_interval",
                "value": 13200
              }
            },
            "unsupported_attributes": {}
          },
          "0x0b05": {
            "endpoint_attribute": "diagnostic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xfc7c": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xfc81": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 0
              }
            },
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "2": {
        "device_type": {
          "name": "OCCUPANCY_SENSOR",
          "id": 263
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0406": {
            "endpoint_attribute": "occupancy",
            "attributes": {
              "0x0000": {
                "attribute_name": "occupancy",
                "value": 1
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "3": {
        "device_type": {
          "name": "LIGHT_SENSOR",
          "id": 262
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0400": {
            "endpoint_attribute": "illuminance",
            "attributes": {
              "0x0000": {
                "attribute_name": "measured_value",
                "value": 16812
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

**Comment by danvolchek** [comment]
I'm also experiencing this

**Comment by Fraighas** [comment]
Hi, Did you guys found something to solve this ?  I'm also experiencing this

**Comment by danvolchek** [comment]
After reading a bunch of threads, it looked to be a problem with the firmware of my Zigbee dongle - that it was too old.

The one I had was using Texas Instruments based firmware, and after more reading, there didn't seem to be an easy way to update TI based dongle firmware.

Instead, I purchased an SI Labs based dongle. The firmware it shipped worked out of the box - I didn't even need to upgrade it (I was going to use https://darkxst.github.io/silabs-firmware-builder/). It just came 30 minutes ago, you commented at the perfect time :)

So in my case it wasn't a zigpy or device handler problem, but rather a dongle firmware problem.

Also note: replacing the dongle required me to re-pair all my zigbee devices. There is a backup/import from backup flow when migrating to a new radio, but it didn't work for me.

**Comment by LukStarkiller** [comment]
Another one, I'm using an SLZB-06 and it gets stuck at configuring.

EDIT: After numerous failed attempts where it got stuck on "configuring," I finally managed to pair it by placing it right next to the SLZB-06 antenna and resetting it just before searching for devices, not the other way around. That said, it took several attempts, and even though it has paired, no entities appear, so I can't use it. This seems odd to me because I've read that many people have managed to get it working directly in ZHA without manually configuring anything.

**Comment by martinhoyer** [comment]
Same
```
File "/usr/local/lib/python3.13/site-packages/zigpy_znp/zigbee/application.py", line 996, in send_packet
    raise DeliveryError(f"Failed to send request: {status!r}", status=status)
zigpy.exceptions.DeliveryError: Failed to send request: <Status.NWK_NO_ROUTE: 205>
```

**Comment by MattWestb** [comment]
<Status.NWK_NO_ROUTE: 205> = Your mesh network is not working OK so it cant find one route to the device.
Update the (TI) coordinator firmware to latest recommended and use only good Zigbee 3 routers in the network for fixing the problem.
And TI coordinator like having end devices as direct child and have problems with latest Zigbee 3 network searing functionality (aka Zigbee PRO 2023).

**Comment by martinhoyer** [comment]
Thanks @MattWestb! I've tried latest firmware as well as one from https://github.com/Koenkk/Z-Stack-firmware/discussions/545.  
I need to read into how to set device as router as I thought it's set automagically :)

**Comment by MattWestb** [comment]
You cant setting one normal sleeping end device as router.
The problem is that some of your network routers is not working OK so the coordinator cant finding one route to the device.
Some tuya devices and old HUE is not reporting there router tables OK and not doing there routing OK.
Try adding it very near the coordinator or open one good router for joining so it using it for the pairing and not other routers that  is making problems.

**Comment by martinhoyer** [comment]
Yep, thanks. I made a mistake of adding them next to coordinator instead of at the intended location. Lesson learned.  
They do pair, after a couple of long attempts, but out of the three vallhorns, only one is actually working, the others will become unavailable, or worse look available, but do not send any useful data. (they are on different routers). 

![Image](https://github.com/user-attachments/assets/af1351be-3d32-4685-8e4b-86c17ebe13a2)

I've optimized the 2.4ghz, migrated to slightly better channel based on results of modified zigpy-cli where I've done mean of 300 scans. Long-shot, knowing all devices are quite close to the two routers, which are close to the coordinator.

**Comment by nicholas-c** [comment]
Chiming in with similar to @martinhoyer 

![Image](https://github.com/user-attachments/assets/a603ed9a-7bd2-47ba-80cf-94df7278524e)

Brand new VALLHORN device gets stuck on "Configuring". Inversely of the solutions outlined above, I've been able to add 2 other Zigbee devices to my network today with no issues (Lumi temp sensor and Ikea bulb).

Some ZHA logs - Removed some bits and bobs related to other devices. Keeping anything related to `0xB9F7` device

```
[0xB9F7](VALLHORN Wireless Motion Sensor): Update device availability -  device available: True - new availability: False - changed: True
[0xB9F7](VALLHORN Wireless Motion Sensor): Device availability changed and device became unavailable
[0xB9F7](VALLHORN Wireless Motion Sensor): Device is not on the network, marking unavailable
[0xB9F7](VALLHORN Wireless Motion Sensor): Update device availability -  device available: False - new availability: False - changed: False
[0xB9F7](VALLHORN Wireless Motion Sensor): started configuration
[0xB9F7:ZDO](VALLHORN Wireless Motion Sensor): 'async_configure' stage succeeded
[0xB9F7](VALLHORN Wireless Motion Sensor): applying quirks custom device configuration
Discovering entities for device: 94:a0:81:ff:fe:ba:e5:34-IKEA of Sweden VALLHORN Wireless Motion Sensor
Discovering entities for endpoint: 94:a0:81:ff:fe:ba:e5:34-1
'update' platform -> 'FirmwareUpdateEntity' using ['ota']
Discovering entities for endpoint: 94:a0:81:ff:fe:ba:e5:34-2
Discovering entities for endpoint: 94:a0:81:ff:fe:ba:e5:34-3
Attempting to discover quirks v2 entities for device: 94:a0:81:ff:fe:ba:e5:34-IKEA of Sweden VALLHORN Wireless Motion Sensor
'switch' platform -> 'ConfigurableAttributeSwitch' using ['cluster_handler_0xfc81']
'number' platform -> 'NumberConfigurationEntity' using ['cluster_handler_0xfc81']

...

[0xB9F7:1:0x1000]: Couldn't get list of groups: Failed to send request: <Status.APS_NOT_AUTHENTICATED: 187>
Previously delayed device request is now running, delayed by 30.29s
Tries remaining: 3
Received a packet: ZigbeePacket(timestamp=datetime.datetime(2025, 5, 19, 14, 5, 12, 679392, tzinfo=datetime.timezone.utc), priority=0, src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC611), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=9, profile_id=0, cluster_id=32817, data=Serialized[b'\t\x00\x10\x0c\x03\x86\xff#\xbc3:<\xb9\x90\x13\xa0\xfe\xff\x14C\x0c\xe0\xce%\x02\x0f\x1f\x86\xff#\xbc3:<\xb9\xce\xb8\xb1\xfe\xff\xf9\xe3\xb4\x92\xd4%\x02\x0f+\x86\xff#\xbc3:<\xb9\x1d\xde=\xfe\xff\x14.\x84\x01\xf3%\x02\x0f)'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=None, rssi=None)

...

[0xB9F7:1:0x0001]: Performing cluster binding
[0xb9f7] Extending timeout for 0x52 request
[0xB9F7:1:0x0000]: Configuring cluster attribute reporting
Emitting event zha_channel_configure_reporting with data ClusterConfigureReportingEvent(cluster_name='Basic', cluster_id=0, attributes={}, cluster_handler_unique_id='94:a0:81:ff:fe:ba:e5:34:1:0x0000', event_type='zha_channel_message', event='zha_channel_configure_reporting') (0 listeners)
[0xB9F7:1:0x0000]: finished cluster handler configuration
[0xB9F7:1:0x0003]: Configuring cluster attribute reporting
Emitting event zha_channel_configure_reporting with data ClusterConfigureReportingEvent(cluster_name='Identify', cluster_id=3, attributes={}, cluster_handler_unique_id='94:a0:81:ff:fe:ba:e5:34:1:0x0003', event_type='zha_channel_message', event='zha_channel_configure_reporting') (0 listeners)
[0xB9F7:1:0x0003]: finished cluster handler configuration
[0xB9F7:1:0x1000] Sending request header: ZCLHeader(frame_control=FrameControl<0x01>(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=False, direction=<Direction.Client_to_Server: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), tsn=83, command_id=65, *direction=<Direction.Client_to_Server: 0>)
[0xB9F7:1:0x1000] Sending request: get_group_identifiers(start_index=0)
[0xb9f7] Extending timeout for 0x53 request
Device concurrency (1) reached, delaying device request (0 enqueued)
[0xB9F7:1:0x0020]: Performing cluster binding
[0xb9f7] Extending timeout for 0x54 request
Device concurrency (1) reached, delaying device request (1 enqueued)
[0xB9F7:1:0x0006]: Performing cluster binding
[0xb9f7] Extending timeout for 0x55 request
Device concurrency (1) reached, delaying device request (2 enqueued)
[0xB9F7:1:0x0019_client]: finished cluster handler configuration
[0xB9F7:1:0x0006_client]: Performing cluster binding
[0xb9f7] Extending timeout for 0x56 request
Device concurrency (1) reached, delaying device request (3 enqueued)
[0xB9F7:1:0x0019_client]: finished cluster handler configuration
[0xB9F7:2:0x0000]: Configuring cluster attribute reporting
Emitting event zha_channel_configure_reporting with data ClusterConfigureReportingEvent(cluster_name='Basic', cluster_id=0, attributes={}, cluster_handler_unique_id='94:a0:81:ff:fe:ba:e5:34:2:0x0000', event_type='zha_channel_message', event='zha_channel_configure_reporting') (0 listeners)
[0xB9F7:2:0x0000]: finished cluster handler configuration
[0xB9F7:2:0x0406]: Performing cluster binding
[0xb9f7] Extending timeout for 0x57 request
Device concurrency (1) reached, delaying device request (4 enqueued)
[0xB9F7:2:0x0003]: Configuring cluster attribute reporting
Emitting event zha_channel_configure_reporting with data ClusterConfigureReportingEvent(cluster_name='Identify', cluster_id=3, attributes={}, cluster_handler_unique_id='94:a0:81:ff:fe:ba:e5:34:2:0x0003', event_type='zha_channel_message', event='zha_channel_configure_reporting') (0 listeners)
[0xB9F7:2:0x0003]: finished cluster handler configuration
[0xB9F7:3:0x0003]: Configuring cluster attribute reporting
Emitting event zha_channel_configure_reporting with data ClusterConfigureReportingEvent(cluster_name='Identify', cluster_id=3, attributes={}, cluster_handler_unique_id='94:a0:81:ff:fe:ba:e5:34:3:0x0003', event_type='zha_channel_message', event='zha_channel_configure_reporting') (0 listeners)
[0xB9F7:3:0x0003]: finished cluster handler configuration
[0xB9F7:3:0x0400]: Performing cluster binding
[0xb9f7] Extending timeout for 0x58 request
Device concurrency (1) reached, delaying device request (5 enqueued)
[0xB9F7:3:0x0000]: Configuring cluster attribute reporting
Emitting event zha_channel_configure_reporting with data ClusterConfigureReportingEvent(cluster_name='Basic', cluster_id=0, attributes={}, cluster_handler_unique_id='94:a0:81:ff:fe:ba:e5:34:3:0x0000', event_type='zha_channel_message', event='zha_channel_configure_reporting') (0 listeners)
[0xB9F7:3:0x0000]: finished cluster handler configuration

...

[0xB9F7:1:0x0001]: Failed to bind 'power' cluster: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/zigpy/device.py", line 381, in request
    return await req.result
           ^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 288, in bind
    res = await self.cluster.bind()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/zigpy/zcl/__init__.py", line 686, in bind
    return await self._endpoint.device.zdo.bind(cluster=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/zigpy/zdo/__init__.py", line 247, in bind
    return await self.Bind_req(
           ^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/zigpy/zdo/__init__.py", line 67, in request
    return await self._device.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/zigpy/device.py", line 380, in request
    async with asyncio_timeout(timeout):
               ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
Emitting event zha_channel_bind with data ClusterBindEvent(cluster_name='Power Configuration', cluster_id=1, success=False, cluster_handler_unique_id='94:a0:81:ff:fe:ba:e5:34:1:0x0001', event_type='zha_channel_message', event='zha_channel_bind') (0 listeners)
[0xB9F7:1:0x0001]: Configuring cluster attribute reporting
[0xB9F7:1:0x0001] Sending request header: ZCLHeader(frame_control=FrameControl<0x00>(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Client_to_Server: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), tsn=90, command_id=<GeneralCommand.Configure_Reporting: 6>, *direction=<Direction.Client_to_Server: 0>)
[0xB9F7:1:0x0001] Sending request: Configure_Reporting(config_records=[AttributeReportingConfig(direction=0, attrid=0x0020, datatype=<DataTypeId.uint8: 32>, min_interval=3600, max_interval=10800, reportable_change=1), AttributeReportingConfig(direction=0, attrid=0x0021, datatype=<DataTypeId.uint8: 32>, min_interval=3600, max_interval=10800, reportable_change=1)])
[0xb9f7] Extending timeout for 0x5a request
Device concurrency (1) reached, delaying device request (7 enqueued)
Previously delayed device request is now running, delayed by 29.35s
Tries remaining: 3
Received a packet: ZigbeePacket(timestamp=datetime.datetime(2025, 5, 19, 14, 5, 11, 383849, tzinfo=datetime.timezone.utc), priority=0, src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xC611), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=8, profile_id=0, cluster_id=32817, data=Serialized[b'\x08\x00\x10\t\x03\x86\xff#\xbc3:<\xb9\x8a4\xfa\xfe\xff\x81\x8eX\xe0T%\x02\x0fR\x86\xff#\xbc3:<\xb9c\xea^\xfe\xff\x14.\x84a{%\x02\x0f%\x86\xff#\xbc3:<\xb9\xc8\x90\xf1\xfe\xff\x81\x8eX\xbe\xae%\x02\x0fR'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=None, rssi=None)
Received a packet: ZigbeePacket(timestamp=datetime.datetime(2025, 5, 19, 14, 5, 11, 714739, tzinfo=datetime.timezone.utc), priority=0, src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x504E), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=0, profile_id=260, cluster_id=768, data=Serialized[b'\x18:\n\x03\x00!2\xb3\x04\x00!\xccL\x00\x00 \x00\x01\x00 \xfe\x07\x00!\x99\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=29, non_member_radius=0, lqi=93, rssi=None)
```
