### ISSUE TITLE
[Device Support Request] Quirky Outlink KWh

### ISSUE THREAD

**Issue by MagnaPilot** [zigpy/zha-device-handlers#334]
Hello, I'd like to request a quirk for the Quirky/Wink Outlink outlets.  Presently, Home Assistant can enumerate the switch and a "power" meter entity, but the power meter device doesn't appear to be reading or parsing the correct cluster and attribute to calculate the load.  It appears to be using  0x0702, 0x0400 "Instantaneous Demand" instead of the value that actually shows the accumulated usage which is 0x0702, 0x0000, "Current Sum Delivered".

If it is possible, as I know this requires a calculation, I'd like to request that at least the correct attribute be visible to HA, more useful would for the correction to KWh and cycled refresh to monitor load usage over a short time.  I have included a link to how the SmartThings Community has adapted the same feature.

https://gist.github.com/mitchpond/4247278f35f3dc639c11
https://github.com/nicjansma/smart-things/blob/master/devicetypes/nicjansma/quirky-outlink/quirky-outlink.groovy

**Device signature - working on this now, will update.

Errors logged currently in HA that may be related:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/sensor.py", line 133, in async_set_state
    value = self.formatter(value)
  File "/usr/src/homeassistant/homeassistant/components/zha/sensor.py", line 270, in formatter
    return self._channel.formatter_function(value)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/channels/smartenergy.py", line 159, in formatter_function
    return self._format_spec.format(value).lstrip()
ValueError: Format specifier missing precision
```

Log/Device Signature when joining to network:

```
[0x0000:zdo] ZDO request ZDOCmd.Mgmt_Permit_Joining_req: [60, <Bool.false: 0>]
[0xf76f:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=182 command_id=Command.Report_Attributes>
[0xf76f:1:0x0006] ZCL request 0x000a: [[<Attribute attrid=0 value=<TypeValue type=Bool, value=Bool.true>>]]
[0xf76f:1:0x0006] Attribute report received: on_off=Bool.true
[0xf76f:1:0x0702] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=183 command_id=Command.Report_Attributes>
[0xf76f:1:0x0702] ZCL request 0x000a: [[<Attribute attrid=1024 value=<TypeValue type=int24s, value=0>>]]
[0xf76f:1:0x0702] Attribute report received: instantaneous_demand=0
[0x0000:zdo] ZDO request ZDOCmd.Mgmt_Permit_Joining_req: [60, <Bool.false: 0>]
Device 0xfb6d (7c:25:e4:00:00:0c:bc:3e) joined the network
[0xfb6d:zdo] ZDO request ZDOCmd.Device_annce: [0xfb6d, 7c:25:e4:00:00:0c:bc:3e, 142]
[0xfb6d] Requesting 'Node Descriptor'
[0xfb6d] Extending timeout for 0x2e request
[0xfb6d:zdo] ZDO request ZDOCmd.Match_Desc_req: [0xfffd, 260, [25], []]
[0xfb6d:zdo] ZDO request ZDOCmd.IEEE_addr_req: [0x0000, 0, 0]
[0xfb6d] Node Descriptor: <Optional byte1=1 byte2=64 mac_capability_flags=142 manufacturer_code=48042 maximum_buffer_size=64 maximum_incoming_transfer_size=0 server_mask=0 maximum_outgoing_transfer_size=0 descriptor_capability_field=3>
[0xfb6d] Discovering endpoints
Ignoring message (b'010001008854025107000201') on cluster 25: unknown endpoint or cluster id: 1
[0xfb6d] Discovered endpoints: [1]
[0xfb6d:1] Discovering endpoint information
[0xfb6d:1] Discovered endpoint information: <SimpleDescriptor endpoint=1 profile=260 device_type=2 device_version=0 input_clusters=[0, 3, 6, 5, 4, 64544, 1794] output_clusters=[25]>
[0xfb6d:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=54 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1] Manufacturer: Quirky
[0xfb6d:1] Model: ZHA Smart Plug
Checking quirks for Quirky ZHA Smart Plug (7c:25:e4:00:00:0c:bc:3e)
Considering <class 'bellows.zigbee.application.EZSPCoordinator'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.gledopto.soposhgu10.SoposhGU10'>
Fail because endpoint list mismatch: {11, 13} {1}
Considering <class 'zhaquirks.lutron.lzl4bwhl01remote.LutronLZL4BWHL01Remote2'>
Fail because profile_id mismatch on at least one endpoint
Considering <class 'zhaquirks.netvox.z308e3ed.Z308E3ED'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.osram.a19twhite.A19TunableWhite'>
Fail because endpoint list mismatch: {3} {1}
Considering <class 'zhaquirks.philips.rom001.PhilipsROM001'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.philips.rwl020.PhilipsRWL020'>
Fail because endpoint list mismatch: {1, 2} {1}
Considering <class 'zhaquirks.philips.rwl021.PhilipsRWL021'>
Fail because endpoint list mismatch: {1, 2} {1}
Considering <class 'zhaquirks.smartthings.multi.SmartthingsMultiPurposeSensor'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.smartthings.tag_v4.SmartThingsTagV4'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.xbee.xbee3_io.XBee3Sensor'>
Fail because endpoint list mismatch: {232, 230} {1}
Considering <class 'zhaquirks.xbee.xbee_io.XBeeSensor'>
Fail because endpoint list mismatch: {232, 230} {1}
Considering <class 'zhaquirks.xiaomi.mija.smoke.MijiaHoneywellSmokeDetectorSensor'>
Fail because device_type mismatch on at least one endpoint
device - 0xfb6d:7c:25:e4:00:00:0c:bc:3e entering async_device_initialized - is_new_join: True
device - 0xfb6d:7c:25:e4:00:00:0c:bc:3e has joined the ZHA zigbee network
[0xfb6d](ZHA Smart Plug): started configuration
[0xfb6d:ZDO](ZHA Smart Plug): 'async_configure' stage succeeded
[0xfb6d:1:0x0006]: bound 'on_off' cluster: Status.SUCCESS
[0xfb6d:1:0x0702] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=58 command_id=Command.Read_Attributes_rsp>
Error calling listener.attribute_updated: unsupported operand type(s) for *: 'uint24_t' and 'NoneType'
[0xfb6d:1:0x0000]: bound 'basic' cluster: Status.SUCCESS
[0xfb6d:1:0x0000]: finished channel configuration
[0xfb6d:1:0x0702] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=64 command_id=Command.Read_Attributes_rsp>
Error calling listener.attribute_updated: unsupported operand type(s) for *: 'uint24_t' and 'NoneType'
[0xfb6d:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=62 command_id=Command.Configure_Reporting_rsp>
[0xfb6d:1:0x0006]: reporting 'on_off' attr on 'on_off' cluster: 0/900/1: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
[0xfb6d:1:0x0006]: finished channel configuration
[0xfb6d:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=66 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1:0x0000]: initializing channel: from_cache: False
[0xfb6d:1:0x0019]: bound 'ota' cluster: Status.SUCCESS
[0xfb6d:1:0x0019]: finished channel configuration
[0xfb6d:1:0x0702] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=68 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=0 command_id=Command.Report_Attributes>
[0xfb6d:1:0x0006] ZCL request 0x000a: [[<Attribute attrid=0 value=<TypeValue type=Bool, value=Bool.true>>]]
[0xfb6d:1:0x0006] Attribute report received: on_off=Bool.true
[0xfb6d:1:0x0702] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=72 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1:0x0702]: bound 'smartenergy_metering' cluster: Status.SUCCESS
[0xfb6d:1:0x0702] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=76 command_id=Command.Configure_Reporting_rsp>
[0xfb6d:1:0x0702]: reporting 'instantaneous_demand' attr on 'smartenergy_metering' cluster: 30/900/1: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
[0xfb6d:1:0x0702]: finished channel configuration
[0xfb6d:1:0x0006]: 'async_configure' stage succeeded
[0xfb6d:1:0x0702]: 'async_configure' stage succeeded
[0xfb6d:1:0x0000]: 'async_configure' stage succeeded
[0xfb6d:1:0x0019]: 'async_configure' stage succeeded
[0xfb6d](ZHA Smart Plug): completed configuration
[0xfb6d](ZHA Smart Plug): stored in registry: ZhaDeviceEntry(name='Quirky ZHA Smart Plug', ieee='7c:25:e4:00:00:0c:bc:3e', last_seen=1586950098.7943282)
[0xfb6d:1:0x0003] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=78 command_id=Command.Default_Response>
[0xfb6d:1:0x0003]: executed 'trigger_effect' command with args: '(2, 0)' kwargs: '{}' result: [64, <Status.UNSUP_CLUSTER_COMMAND: 129>]
[0xfb6d](ZHA Smart Plug): started initialization
[0xfb6d:ZDO](ZHA Smart Plug): 'async_initialize' stage succeeded
[0xfb6d:1:0x0702]: initializing channel: from_cache: False
[0xfb6d:1:0x0006]: attempting to update onoff state - from cache: False
[0xfb6d:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=80 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1:0x0006]: initializing channel: from_cache: False
[0xfb6d:1:0x0702] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=82 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1:0x0019]: initializing channel: from_cache: False
[0xfb6d:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=86 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=88 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=84 command_id=Command.Read_Attributes_rsp>
[0xfb6d:1:0x0000]: initializing channel: from_cache: False
[0xfb6d:1:0x0006]: 'async_initialize' stage succeeded
[0xfb6d:1:0x0702]: 'async_initialize' stage succeeded
[0xfb6d:1:0x0000]: 'async_initialize' stage succeeded
[0xfb6d:1:0x0019]: 'async_initialize' stage succeeded
[0xfb6d](ZHA Smart Plug): power source: Mains
[0xfb6d](ZHA Smart Plug): completed initialization
[0xfb6d:1:0x0702] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=1 command_id=Command.Report_Attributes>
[0xfb6d:1:0x0702] ZCL request 0x000a: [[<Attribute attrid=1024 value=<TypeValue type=int24s, value=0>>]]
[0xfb6d:1:0x0702] Attribute report received: instantaneous_demand=0
```

**Comment by Adminiuga** [comment]
ATM the problem is with ZHA sensor platform which only supports one attribute per cluster.

**Comment by MagnaPilot** [comment]
I by no means am educated enough in Zigbee to be arguing, I'm more just curious when I ask.  Are you saying that because ZHA is currently using the x0400 attribute, it cannot use the x0000 attribute because both reside under the 0x0702 cluster?   I only ask for my own curiosity.  I'm not sure what the x0400 attribute is used for for on this device, none of my Outlink's report any data from that attribute.
