### ISSUE TITLE
[BUG] Error message when modifying configuration for Tuya presence sensor devices

### ISSUE THREAD

**Issue by wesleysee** [zigpy/zha-device-handlers#3520]
### Bug description

When trying to change the configuration for my Tuya Zigbee devices, I encounter the following error. I'm unsure if the changes themselves actually persist, they seem to do so in some of my devices, but not in others, though this could also be due to the custom quirk used.

```
Failed to convert attr_value=730.0 from type <class 'zigpy.types.basic.Single'> to int | str
```

This started occurring after a recent Home Assistant update. Also reported in https://github.com/home-assistant/core/issues/130218

### Steps to reproduce

1. Go to any Tuya Zigbee device. I only have presence sensor Tuya devices, not sure if this happens for any Tuya device.
2. Try to change the value for any configuration

### Expected behavior

Error message should not be encountered

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

<img width="773" alt="Screenshot 2024-11-17 at 5 16 30 PM" src="https://github.com/user-attachments/assets/5e05fe5c-3370-464a-bdd8-4e3cb8fdbf29">

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": {
    "logical_type": 1,
    "complex_descriptor_available": 0,
    "user_descriptor_available": 0,
    "reserved": 0,
    "aps_flags": 0,
    "frequency_band": 8,
    "mac_capability_flags": 142,
    "manufacturer_code": 4417,
    "maximum_buffer_size": 66,
    "maximum_incoming_transfer_size": 66,
    "server_mask": 10752,
    "maximum_outgoing_transfer_size": 66,
    "descriptor_capability_field": 0
  },
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0107",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x000c",
        "0x000d",
        "0x0400",
        "0x0406",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": "0x0104",
      "device_type": "0x0007",
      "input_clusters": [
        "0x000d"
      ],
      "output_clusters": []
    },
    "3": {
      "profile_id": "0x0104",
      "device_type": "0x0007",
      "input_clusters": [
        "0x000d"
      ],
      "output_clusters": []
    },
    "4": {
      "profile_id": "0x0104",
      "device_type": "0x0007",
      "input_clusters": [
        "0x000d"
      ],
      "output_clusters": []
    },
    "5": {
      "profile_id": "0x0104",
      "device_type": "0x0007",
      "input_clusters": [
        "0x000d"
      ],
      "output_clusters": []
    },
    "242": {
      "profile_id": "0xa1e0",
      "device_type": "0x0061",
      "input_clusters": [],
      "output_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZE204_ya4ft0w4",
  "model": "TS0601",
  "class": "tuya_ts0601_TZE204_ya4ft0w4.TuyaMmwRadarOccupancy"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
```

</details>

### Logs

<details><summary>Logs</summary>

```python
2024-11-17 17:17:19.191 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [23430409094912] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/zigpy/types/struct.py", line 50, in _convert_type
    return field_type(value)
           ^^^^^^^^^^^^^^^^^
TypeError: 'types.UnionType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 122, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/usr/src/homeassistant/homeassistant/components/zha/helpers.py", line 1335, in handler
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/number.py", line 88, in async_set_native_value
    await self.entity_data.entity.async_set_native_value(value=value)
  File "/usr/local/lib/python3.12/site-packages/zha/application/platforms/number/__init__.py", line 173, in async_set_native_value
    await self._analog_output_cluster_handler.async_set_present_value(float(value))
  File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/general.py", line 161, in async_set_present_value
    await self.write_attributes_safe(
  File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 614, in write_attributes_safe
    res = await self.write_attributes(attributes, manufacturer=manufacturer)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 85, in wrapper
    return await RETRYABLE_REQUEST_DECORATOR(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/util.py", line 136, in retry
    return await func()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zhaquirks/tuya/mcu/__init__.py", line 111, in write_attributes
    cluster_data = TuyaClusterData(
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/types/struct.py", line 118, in __new__
    setattr(instance, name, field._convert_type(value, struct=instance))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/types/struct.py", line 52, in _convert_type
    raise ValueError(
ValueError: Failed to convert attr_value=730.0 from type <class 'zigpy.types.basic.Single'> to int | str
```

</details>

### Additional information

From what I can tell from the logs, the issue seems to be because of this [line](https://github.com/zigpy/zha-device-handlers/blame/dev/zhaquirks/tuya/mcu/__init__.py#L68C5-L68C54) in `TuyaClusterData`

```
attr_value: int | str  # Maybe also others types?
```

zigpy seems to be [attempting](https://github.com/zigpy/zigpy/blob/dev/zigpy/types/struct.py#L50) to cast the value to the type, but this operation doesn't seem to work for union types.

The above line was introduced to `TuyaClusterData` in a recent [PR](https://github.com/zigpy/zha-device-handlers/pull/3394), which seems to line up with the timeline.

If I revert the above line to the below, I no longer see the error.

```
attr_value: int 
```

**Comment by pfh-47** [comment]
Hi,

"If I revert the above line to the below ...". Please can you explain how to do this? Where do I find the TuyaClusterData code?

FYI I'm the author of home-assistant/core#130218 - not getting any attention :(

**Comment by prairiesnpr** [comment]
We can revert this for now. It does need to be updated though, we shouldn't be attempting to convert every value to an integer.

**Comment by pfh-47** [comment]
Thank you
