### ISSUE TITLE
[BUG] Tuya TS130F Curtain (Roller Shutter) - not setting current_position_lift_percentage

### ISSUE THREAD

**Issue by mkz212** [zigpy/zha-device-handlers#3600]
### Bug description

Tuya TS130F TZ3000_eg7awg6a (single Roller Shutter) (Quirk: zhaquirks.tuya.ts130f.TuyaTS130GP) not saving  current_position_lift_percentage.

Exactly same device, but Double Roller Shutter, Tuya TS130F _TZ3000_j1xl73iw (Quirk: zhaquirks.tuya.ts130f.TuyaTS130Double_GP_ESTC) works ok.

### Steps to reproduce

When I set position e.g. to 52% target lift position is 52 and curtain is moving to this position, but current_position_lift_percentage is 100. So after a while it shows wrong position in HA, even though the roller blind is in the correct position.

### Expected behavior

Fix position

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

In fact, this blind is closed. But as you can see, the target lift position is ok but current_position_lift_percentage is wrong and so status in HA is wrong - it shows closed blind as open.

![IMG_7868](https://github.com/user-attachments/assets/09547b20-44a4-4740-8ebe-ab429305f2d0)
![IMG_7869](https://github.com/user-attachments/assets/915a1b5a-4500-4327-96b1-c23b14598ac4)

And this is how it looks for working device (TS130F _TZ3000_j1xl73iw):

![IMG_7870](https://github.com/user-attachments/assets/683c26df-87f6-4962-a6de-79291a778fd6)
![IMG_7871](https://github.com/user-attachments/assets/1b74d0d0-725c-47f1-837e-06fe57d83dd9)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": {
    "logical_type": 1,
    "complex_descriptor_available": 0,
    "user_descriptor_available": 0,
    "reserved": 0,
    "aps_flags": 0,
    "frequency_band": 8,
    "mac_capability_flags": 142,
    "manufacturer_code": 4417,
    "maximum_buffer_size": 66,
    "maximum_incoming_transfer_size": 66,
    "server_mask": 10752,
    "maximum_outgoing_transfer_size": 66,
    "descriptor_capability_field": 0
  },
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0202",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0102"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": "0xa1e0",
      "device_type": "0x0061",
      "input_clusters": [],
      "output_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZ3000_eg7awg6a",
  "model": "TS130F",
  "class": "zhaquirks.tuya.ts130f.TuyaTS130GP"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
File "/usr/local/lib/python3.13/site-packages/zigpy/device.py", line 378, in request
    await send_request()
  File "/usr/local/lib/python3.13/site-packages/zigpy/application.py", line 835, in request
    await self.send_packet(
    ...<14 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/bellows/zigbee/application.py", line 857, in send_packet
    raise zigpy.exceptions.DeliveryError(
        f"Failed to deliver message: {send_status!r}", send_status
    )
zigpy.exceptions.DeliveryError: Failed to deliver message: <sl_Status.ZIGBEE_DELIVERY_FAILED: 3074>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/zha/zigbee/cluster_handlers/general.py", line 633, in check_in_response
    await self.fast_poll_stop()
  File "/usr/local/lib/python3.13/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 84, in wrapper
    with wrap_zigpy_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 76, in wrap_zigpy_exceptions
    raise ZHAException(message) from exc
zha.exceptions.ZHAException: Failed to send request: Failed to deliver message: <sl_Status.ZIGBEE_DELIVERY_FAILED: 3074>
```

```python

2024-12-09 07:36:21.505 DEBUG (MainThread) [zigpy.zcl] [0x0D63:1:0x0102] Attribute report received: current_position_lift_percentage=54
2024-12-09 07:36:21.505 DEBUG (MainThread) [zha.zigbee.cluster_handlers] [0x0D63:1:0x0102]: cluster_handler[window_covering] attribute_updated - cluster[Window Covering] attr[current_position_lift_percentage] value[46]
```

</details>

### Additional information

Home Assistant core-2024.12.1
No updates for system. 
No firmware updates for devices.

**Comment by mkz212** [comment]
Using automation to set cluster works.

**Comment by dabeschte** [comment]
hey @mkz212: you mentioned that using an automation works. what do you mean with that? 
My problem is that the position is always wrong after a couple hours independent of if I used HA or my hardware switches connected to the curtain module to control them.

Is there a solution to always save the current lift position with automations?

**Comment by mkz212** [comment]
This is my automation as workaround for this. This one automation fix all covers. Just replace triggers for yours. 

```python

alias: Napraw rolety
description: ""
triggers:
  - entity_id:
      - cover.m2_biuro_roleta
      - cover.m2_lazienka_roleta
      - cover.m2_kuchnia_wyspa_roleta
      - cover.m3_lazienka_roleta
      - cover.m1_salon_l_roleta
      - cover.m1_salon_r_roleta
      - cover.m1_sypialnia_roleta
      - cover.m4_roleta
      - cover.m5_roleta
    trigger: state
    to:
      - open
      - closed
    for:
      hours: 0
      minutes: 0
      seconds: 15
conditions: []
actions:
  - variables:
      device: "{{ trigger.entity_id }}"
      ieee: >-
        {{ device_attr(device, 'identifiers') | selectattr(0,'eq','zha') |
        map(attribute=1) | first }}
      position: "{{ state_attr(device, 'current_position') }}"
  - data:
      ieee: "{{ ieee }}"
      endpoint_id: 1
      cluster_id: 258
      cluster_type: in
      attribute: 8
      value: "{{ position }}"
    action: zha.set_zigbee_cluster_attribute
mode: parallel
max: 10

```

**Comment by pchenriques** [comment]
It works, @mkz212. Thanks for the code. But for the absolut fix for the issue, what would we could expect from this open ticket?

**Comment by mkz212** [comment]
> It works, [@mkz212](https://github.com/mkz212). Thanks for the code. But for the absolut fix for the issue, what would we could expect from this open ticket?

I realize that zigbee is not perfect. I used to have zwave and I didn't have such problems there, but zwave is 5-7 times more expensive. 

In general, the biggest problems with zigbee that I see are:
- some blinds do not save position cluster
- there is only one calibration of the roller blind, the same for the movement in the top and the same for the movement in the down - and the movement time in the top is always minimally longer
- there is no queue, if you send a lot of commands at once, not every one works. I think it is optimal for a maximum of 5 commands at a time and a 2-second break
- there is no option to automatically reconfigure whole zigbee mesh.

Returning to this Issue - I don't know what causes some of the blinds to write the cluster correctly and some not.

**Comment by pchenriques** [comment]
@mkz212 , thanks for the feedback. Hopefully we will get the fix at quirk level (I've read that the issue isn't happening while using MQTT).
Meanwhile, I'm following (again) your suggestion of splitting into device groups (I have 8 blinds and frequently get communication errors).

**Comment by mkz212** [comment]
> [@mkz212](https://github.com/mkz212) , thanks for the feedback. Hopefully we will get the fix at quirk level (I've read that the issue isn't happening while using MQTT). Meanwhile, I'm following (again) your suggestion of splitting into device groups (I have 8 blinds and frequently get communication errors).

You don't have to make groups - all you have to do is divide commands in automations - so that it sends max 4-5 commands, then 2-3 seconds breaks and next commands. The second issue is in my case is that roller shutters devices have a poor range, so I had to add signal repeaters (Ikea has cheap outlets that works as repeaters).

**Comment by dabeschte** [comment]
@mkz212's solution fixed it  90% of the time for me, but not always.
I bought a second zigbee adapter for z2m and can confirm that the position is always correct with that. My sonoff humidity sensor is also more stable with it. But z2h has worked well for me for everything so far except these 2 devices

**Comment by mkz212** [comment]
> [@mkz212](https://github.com/mkz212)'s solution fixed it 90% of the time for me, but not always. I bought a second zigbee adapter for z2m and can confirm that the position is always correct with that. My sonoff humidity sensor is also more stable with it. But z2h has worked well for me for everything so far except these 2 devices

I know that my automation for repair will not work if the device has a poor range or if the zigbee network is busy (too many commands at once). I know that there is no queue mechanism in zha - if there are too many commands at the same time, some do not work. As far as I know, z2m has a queue mechanism, so there is no such problem.


### From AI:

Yes, Zigbee2MQTT (Z2M) has a queue mechanism that is used to manage messages sent to Zigbee devices. This mechanism operates based on the MQTT protocol and allows for queuing commands, which is particularly useful when dealing with a large number of devices or when some devices may be temporarily unavailable (e.g., due to a weak signal or being in sleep mode to save energy).

In practice, Z2M uses an internal queue to store commands, such as changing a device's state (e.g., turning a bulb on/off), until they are successfully delivered or processed. If a device doesn't respond immediately, the command remains in the queue and is retried according to the configuration (e.g., the number of retries or timeout settings).
