### ISSUE TITLE
[Device Support Request] Scene Switch 4 Gang TS0044 doesn't update

### ISSUE THREAD

**Issue by CharlesH75** [zigpy/zha-device-handlers#699]
I have a Tuya Zigbee 4 Button Scene Switch that i have successfully paired to ZHA (with Sonoff Zigbee Bridge and also tried with a CC2531 stick).
This is exactly the model of the device: https://zigbee.blakadder.com/Earda_ESW-0ZAA-EU.html

**The bug**
But when I click on buttons of the device, the switch are not updated and I get the following warning
`[zigpy.zcl] [0xb2f7:3:0x0006] Unknown cluster-specific command 253`

And when I enable the switch through HA, I get the following error:
`
2021-01-05 18:16:33 ERROR (MainThread) [zigpy_znp.uart] Received an exception while passing frame to API
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/uart.py", line 77, in data_received
    self._api.frame_received(frame.payload)
  File "/srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/api.py", line 334, in frame_received
    command = command_cls.from_frame(frame)
  File "/srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/types/commands.py", line 412, in from_frame
    params[param.name], data = param.type.deserialize(data)
  File "/srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/types/struct.py", line 206, in deserialize
    value, data = field.get_type_for(instance).deserialize(data)
  File "/srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/types/basic.py", line 79, in deserialize
    raise ValueError(f"Data is too short to contain {cls._size} bytes")
ValueError: Data is too short to contain 4 bytes
`

**Screenshots**
![image](https://user-images.githubusercontent.com/61110764/103678013-4e6cdf00-4f83-11eb-8389-0c489549c9a6.png)

**Device signature**
`
{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0000",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0006"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0000",
      "in_clusters": [
        "0x0001",
        "0x0006"
      ],
      "out_clusters": []
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x0000",
      "in_clusters": [
        "0x0001",
        "0x0006"
      ],
      "out_clusters": []
    },
    "4": {
      "profile_id": 260,
      "device_type": "0x0000",
      "in_clusters": [
        "0x0001",
        "0x0006"
      ],
      "out_clusters": []
    }
  },
  "manufacturer": "_TZ3000_vp6clf9d",
  "model": "TS0044",
  "class": "zigpy.device.Device"
}
`

**Comment by CharlesH75** [comment]
## This is the debug log when I enable the switch in HA
```
2021-01-05 21:08:19 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=switch, service=turn_on, service_data=entity_id=switch.tz3000_vp6clf9d_ts0044_b7a0c8fe_on_off>

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy.device] [0xb2f7] Extending timeout for 0x01 request

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] Creating one-shot listener OneShotResponseListener(matching_commands=(AF.DataConfirm.Callback(Status=None, Endpoint=None, TSN=1),), future=<Future pending cb=[ZNP.wait_for_responses.<locals>.<lambda>() at /srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/api.py:436]>)

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] Sending request: AF.DataRequestExt.Req(DstAddrModeAddress=AddrModeAddress(mode=<AddrMode.NWK: 2>, address=0xB2F7), DstEndpoint=1, DstPanId=0x0000, SrcEndpoint=1, ClusterId=6, TSN=1, Options=<TransmitOptions.SUPPRESS_ROUTE_DISC_NETWORK|ACK_REQUEST: 48>, Radius=30, Data=b'\x01\x01\x01')

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] Creating one-shot listener OneShotResponseListener(matching_commands=(AF.DataRequestExt.Rsp(Status=None), RPCError.CommandNotRecognized.Rsp(ErrorCode=None, RequestHeader=CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SREQ))), future=<Future pending cb=[ZNP.wait_for_responses.<locals>.<lambda>() at /srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/api.py:436, <TaskWakeupMethWrapper object at 0xa76047c0>()]>)

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.uart] Sending data: b'\xFE\x17\x24\x02\x02\xF7\xB2\x00\x00\x00\x00\x00\x00\x01\x00\x00\x01\x06\x00\x01\x30\x1E\x03\x00\x01\x01\x01\x5D'
2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.uart] Received data: b'\xFE\x01\x64\x02\x00\x67'
2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.uart] Parsed frame: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SRSP), data=b'\x00'))

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.DataRequestExt.Rsp(Status=<Status.SUCCESS: 0>)

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] AF.DataRequestExt.Rsp(Status=<Status.SUCCESS: 0>) matches OneShotResponseListener(matching_commands=(AF.DataRequestExt.Rsp(Status=None), RPCError.CommandNotRecognized.Rsp(ErrorCode=None, RequestHeader=CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SREQ))), future=<Future finished result=AF.DataReques...s.SUCCESS: 0>)>)

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] Removing listener OneShotResponseListener(matching_commands=(AF.DataRequestExt.Rsp(Status=None), RPCError.CommandNotRecognized.Rsp(ErrorCode=None, RequestHeader=CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SREQ))), future=<Future finished result=AF.DataReques...s.SUCCESS: 0>)>)

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] Cleaning up empty listener list for header CommandHeader(id=0x00, subsystem=Subsystem.RPCError, type=CommandType.SRSP)

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] Cleaning up empty listener list for header CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SRSP)

2021-01-05 21:08:19 DEBUG (MainThread) [zigpy_znp.api] There are 5 callbacks and 1 one-shot listeners remaining

2021-01-05 21:08:24 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](CC2531, Z-Stack Home 1.2): Attempting to checkin with device - missed checkins: 1

2021-01-05 21:08:24 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](CC2531, Z-Stack Home 1.2): does not have a mandatory basic cluster

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.uart] Received data: b'\xFE\x03\x44\x80\xF0\x01\x01\x37'

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.uart] Parsed frame: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0x80, subsystem=Subsystem.AF, type=CommandType.AREQ), data=b'\xF0\x01\x01'))

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.DataConfirm.Callback(Status=<Status.MAC_TRANSACTION_EXPIRED: 240>, Endpoint=1, TSN=1)

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.api] AF.DataConfirm.Callback(Status=<Status.MAC_TRANSACTION_EXPIRED: 240>, Endpoint=1, TSN=1) matches OneShotResponseListener(matching_commands=(AF.DataConfirm.Callback(Status=None, Endpoint=None, TSN=1),), future=<Future finished result=AF.DataConfir...oint=1, TSN=1)>)

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.api] Removing listener OneShotResponseListener(matching_commands=(AF.DataConfirm.Callback(Status=None, Endpoint=None, TSN=1),), future=<Future finished result=AF.DataConfir...oint=1, TSN=1)>)

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.api] Cleaning up empty listener list for header CommandHeader(id=0x80, subsystem=Subsystem.AF, type=CommandType.AREQ)

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.api] There are 5 callbacks and 0 one-shot listeners remaining

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.api] Removing listener OneShotResponseListener(matching_commands=(AF.DataConfirm.Callback(Status=None, Endpoint=None, TSN=1),), future=<Future finished result=AF.DataConfir...oint=1, TSN=1)>)

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.api] Cleaning up empty listener list for header CommandHeader(id=0x80, subsystem=Subsystem.AF, type=CommandType.AREQ)

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.api] There are 5 callbacks and 0 one-shot listeners remaining

2021-01-05 21:08:26 DEBUG (MainThread) [zigpy_znp.zigbee.application] Request failed (Unsuccessful request status code: <Status.MAC_TRANSACTION_EXPIRED: 240>), retry attempt 1 of 5

2021-01-05 21:08:27 INFO (Thread-12) [pyhap.hap_server] Got connection with ('192.168.1.31', 49300).

2021-01-05 21:08:27 INFO (Thread-13) [pyhap.hap_server] 192.168.1.31 - "POST /pair-verify HTTP/1.1" 200 -

2021-01-05 21:08:27 INFO (Thread-13) [pyhap.hap_server] 192.168.1.31 - "POST /pair-verify HTTP/1.1" 200 -

2021-01-05 21:08:27 INFO (Thread-13) [pyhap.hap_server] 192.168.1.31 - "GET /accessories HTTP/1.1" 200 -

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] Creating one-shot listener OneShotResponseListener(matching_commands=(AF.DataConfirm.Callback(Status=None, Endpoint=None, TSN=1),), future=<Future pending cb=[ZNP.wait_for_responses.<locals>.<lambda>() at /srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/api.py:436]>)

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] Sending request: AF.DataRequestExt.Req(DstAddrModeAddress=AddrModeAddress(mode=<AddrMode.NWK: 2>, address=0xB2F7), DstEndpoint=1, DstPanId=0x0000, SrcEndpoint=1, ClusterId=6, TSN=1, Options=<TransmitOptions.SUPPRESS_ROUTE_DISC_NETWORK|ACK_REQUEST: 48>, Radius=30, Data=b'\x01\x01\x01')
2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] Creating one-shot listener OneShotResponseListener(matching_commands=(AF.DataRequestExt.Rsp(Status=None), RPCError.CommandNotRecognized.Rsp(ErrorCode=None, RequestHeader=CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SREQ))), future=<Future pending cb=[ZNP.wait_for_responses.<locals>.<lambda>() at /srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/api.py:436, <TaskWakeupMethWrapper object at 0xaa6b1928>()]>)

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.uart] Sending data: b'\xFE\x17\x24\x02\x02\xF7\xB2\x00\x00\x00\x00\x00\x00\x01\x00\x00\x01\x06\x00\x01\x30\x1E\x03\x00\x01\x01\x01\x5D'

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.uart] Received data: b'\xFE\x01\x64\x02\x00\x67'

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.uart] Parsed frame: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SRSP), data=b'\x00'))

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.DataRequestExt.Rsp(Status=<Status.SUCCESS: 0>)

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] AF.DataRequestExt.Rsp(Status=<Status.SUCCESS: 0>) matches OneShotResponseListener(matching_commands=(AF.DataRequestExt.Rsp(Status=None), RPCError.CommandNotRecognized.Rsp(ErrorCode=None, RequestHeader=CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SREQ))), future=<Future finished result=AF.DataReques...s.SUCCESS: 0>)>)

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] Removing listener OneShotResponseListener(matching_commands=(AF.DataRequestExt.Rsp(Status=None), RPCError.CommandNotRecognized.Rsp(ErrorCode=None, RequestHeader=CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SREQ))), future=<Future finished result=AF.DataReques...s.SUCCESS: 0>)>)

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] Cleaning up empty listener list for header CommandHeader(id=0x00, subsystem=Subsystem.RPCError, type=CommandType.SRSP)

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] Cleaning up empty listener list for header CommandHeader(id=0x02, subsystem=Subsystem.AF, type=CommandType.SRSP)

2021-01-05 21:08:28 DEBUG (MainThread) [zigpy_znp.api] There are 5 callbacks and 1 one-shot listeners remaining

2021-01-05 21:08:29 DEBUG (MainThread) [homeassistant.core] Service did not complete before timeout: <ServiceCall switch.turn_on (c:096059b267f819861d3fe1f04c5b05c4): entity_id=['switch.tz3000_vp6clf9d_ts0044_b7a0c8fe_on_off']>

2021-01-05 21:08:30 INFO (Thread-12) [pyhap.hap_server] Got connection with ('192.168.1.83', 57029).

2021-01-05 21:08:30 INFO (Thread-14) [pyhap.hap_server] 192.168.1.83 - "POST /pair-verify HTTP/1.1" 200 -

2021-01-05 21:08:30 INFO (Thread-14) [pyhap.hap_server] 192.168.1.83 - "POST /pair-verify HTTP/1.1" 200 -

2021-01-05 21:08:30 INFO (Thread-14) [pyhap.hap_server] 192.168.1.83 - "GET /accessories HTTP/1.1" 200 -

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.uart] Received data: b'\xFE\x03\x44\x80\xF0\x01\x01\x37'

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.uart] Parsed frame: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0x80, subsystem=Subsystem.AF, type=CommandType.AREQ), data=b'\xF0\x01\x01'))

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.DataConfirm.Callback(Status=<Status.MAC_TRANSACTION_EXPIRED: 240>, Endpoint=1, TSN=1)

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] AF.DataConfirm.Callback(Status=<Status.MAC_TRANSACTION_EXPIRED: 240>, Endpoint=1, TSN=1) matches OneShotResponseListener(matching_commands=(AF.DataConfirm.Callback(Status=None, Endpoint=None, TSN=1),), future=<Future finished result=AF.DataConfir...oint=1, TSN=1)>)

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] Removing listener OneShotResponseListener(matching_commands=(AF.DataConfirm.Callback(Status=None, Endpoint=None, TSN=1),), future=<Future finished result=AF.DataConfir...oint=1, TSN=1)>)

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] Cleaning up empty listener list for header CommandHeader(id=0x80, subsystem=Subsystem.AF, type=CommandType.AREQ)

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] There are 5 callbacks and 0 one-shot listeners remaining

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] Removing listener OneShotResponseListener(matching_commands=(AF.DataConfirm.Callback(Status=None, Endpoint=None, TSN=1),), future=<Future finished result=AF.DataConfir...oint=1, TSN=1)>)

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] Cleaning up empty listener list for header CommandHeader(id=0x80, subsystem=Subsystem.AF, type=CommandType.AREQ)

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] There are 5 callbacks and 0 one-shot listeners remaining

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] Sending request: Util.AssocGetWithAddress.Req(IEEE=5c:02:72:ff:fe:c8:a0:b7, NWK=0xB2F7)

2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.api] Creating one-shot listener OneShotResponseListener(matching_commands=(Util.AssocGetWithAddress.Rsp(Device=None), RPCError.CommandNotRecognized.Rsp(ErrorCode=None, RequestHeader=CommandHeader(id=0x4A, subsystem=Subsystem.UTIL, type=CommandType.SREQ))), future=<Future pending cb=[ZNP.wait_for_responses.<locals>.<lambda>() at /srv/homeassistant/lib/python3.8/site-packages/zigpy_znp/api.py:436, <TaskWakeupMethWrapper object at 0xa76042e0>()]>)
2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.uart] Sending data: b'\xFE\x0A\x27\x4A\xB7\xA0\xC8\xFE\xFF\x72\x02\x5C\xF7\xB2\xD0'
2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.uart] Received data: b'\xFE\x1C\x67\x4A\xF7\xB2\x00\x00\x01\x08\x00\x00\x02\x01\xAA\x00\x00\x00\x00\x00\xF7\x02\x0A\xEC\xF2\x05\x2B\xF7\x00\x0E\xE4\xF3\xF5'
2021-01-05 21:08:34 DEBUG (MainThread) [zigpy_znp.uart] Parsed frame: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0x4A, subsystem=Subsystem.UTIL, type=CommandType.SRSP), data=b'\xF7\xB2\x00\x00\x01\x08\x00\x00\x02\x01\xAA\x00\x00\x00\x00\x00\xF7\x02\x0A\xEC\xF2\x05\x2B\xF7\x00\x0E\xE4\xF3'))

2021-01-05 21:08:34 ERROR (MainThread) [zigpy_znp.uart] Received an exception while passing frame to API
```

## This is the debug log when I click directly on the switch:
```
2021-01-05 21:12:10 DEBUG (MainThread) [zigpy_znp.uart] Received data: b'\xFE\x18\x44\x81\x00\x00\x06\x00\xF7\xB2\x02\x01\x00\x76\x00\xBD\x05\x0E\x00\x00\x04\x01\x1A\xFD\x00\xF7\xB2\x1D\xE7'

2021-01-05 21:12:10 DEBUG (MainThread) [zigpy_znp.uart] Parsed frame: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0x81, subsystem=Subsystem.AF, type=CommandType.AREQ), data=b'\x00\x00\x06\x00\xF7\xB2\x02\x01\x00\x76\x00\xBD\x05\x0E\x00\x00\x04\x01\x1A\xFD\x00\xF7\xB2\x1D'))

2021-01-05 21:12:10 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=6, SrcAddr=0xB2F7, SrcEndpoint=2, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=118, SecurityUse=<Bool.false: 0>, TimeStamp=918973, TSN=0, Data=b'\x01\x1A\xFD\x00', MacSrcAddr=0xB2F7, MsgResultRadius=29)
2021-01-05 21:12:10 DEBUG (MainThread) [zigpy.zcl] [0xb2f7:2:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=False disable_default_response=False> manufacturer=None tsn=26 command_id=253>

2021-01-05 21:12:10 WARNING (MainThread) [zigpy.zcl] [0xb2f7:2:0x0006] Unknown cluster-specific command 253

2021-01-05 21:12:10 DEBUG (MainThread) [zigpy.zcl] [0xb2f7:2:0x0006] ZCL request 0x00fd: b'\x00'

2021-01-05 21:12:10 DEBUG (MainThread) [zigpy.zcl] [0xb2f7:2:0x0006] No handler for cluster command 253

2021-01-05 21:12:10 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0xB2F7:2:0x0006]: received '253' command with b'\x00' args on cluster_id '6' tsn '26'

2021-01-05 21:12:10 DEBUG (MainThread) [zigpy_znp.api] AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=6, SrcAddr=0xB2F7, SrcEndpoint=2, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=118, SecurityUse=<Bool.false: 0>, TimeStamp=918973, TSN=0, Data=b'\x01\x1A\xFD\x00', MacSrcAddr=0xB2F7, MsgResultRadius=29) matches CallbackResponseListener(matching_commands=(AF.IncomingMsg.Callback(GroupId=None, ClusterId=None, SrcAddr=None, SrcEndpoint=None, DstEndpoint=None, WasBroadcast=None, LQI=None, SecurityUse=None, TimeStamp=None, TSN=None, Data=None, MacSrcAddr=None, MsgResultRadius=None),), callback=<bound method ControllerApplication.on_af_message of <zigpy_znp.zigbee.application.ControllerApplication object at 0xacfb9310>>)

2021-01-05 21:12:11 DEBUG (MainThread) [zigpy_znp.uart] Received data: b'\xFE\x18\x44\x81\x00\x00\x06\x00\xF7\xB2\x02\x01\x00\x73\x00\x13\x12\x0E\x00\x00\x04\x01\x1A\xFD\x00\xF7\xB2\x1D\x5B'

2021-01-05 21:12:11 DEBUG (MainThread) [zigpy_znp.uart] Parsed frame: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0x81, subsystem=Subsystem.AF, type=CommandType.AREQ), data=b'\x00\x00\x06\x00\xF7\xB2\x02\x01\x00\x73\x00\x13\x12\x0E\x00\x00\x04\x01\x1A\xFD\x00\xF7\xB2\x1D'))

2021-01-05 21:12:11 DEBUG (MainThread) [zigpy_znp.api] Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=6, SrcAddr=0xB2F7, SrcEndpoint=2, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=115, SecurityUse=<Bool.false: 0>, TimeStamp=922131, TSN=0, Data=b'\x01\x1A\xFD\x00', MacSrcAddr=0xB2F7, MsgResultRadius=29)

2021-01-05 21:12:11 DEBUG (MainThread) [zigpy.zcl] [0xb2f7:2:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=False disable_default_response=False> manufacturer=None tsn=26 command_id=253>

2021-01-05 21:12:11 WARNING (MainThread) [zigpy.zcl] [0xb2f7:2:0x0006] Unknown cluster-specific command 253

2021-01-05 21:12:11 DEBUG (MainThread) [zigpy.zcl] [0xb2f7:2:0x0006] ZCL request 0x00fd: b'\x00'

2021-01-05 21:12:11 DEBUG (MainThread) [zigpy.zcl] [0xb2f7:2:0x0006] No handler for cluster command 253

2021-01-05 21:12:11 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0xB2F7:2:0x0006]: received '253' command with b'\x00' args on cluster_id '6' tsn '26'

2021-01-05 21:12:11 DEBUG (MainThread) [zigpy_znp.api] AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=6, SrcAddr=0xB2F7, SrcEndpoint=2, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=115, SecurityUse=<Bool.false: 0>, TimeStamp=922131, TSN=0, Data=b'\x01\x1A\xFD\x00', MacSrcAddr=0xB2F7, MsgResultRadius=29) matches CallbackResponseListener(matching_commands=(AF.IncomingMsg.Callback(GroupId=None, ClusterId=None, SrcAddr=None, SrcEndpoint=None, DstEndpoint=None, WasBroadcast=None, LQI=None, SecurityUse=None, TimeStamp=None, TSN=None, Data=None, MacSrcAddr=None, MsgResultRadius=None),), callback=<bound method ControllerApplication.on_af_message of <zigpy_znp.zigbee.application.ControllerApplication object at 0xacfb9310>>)
```

**Comment by CharlesH75** [comment]
After upgrading to the dev version of HA, it finally works fine
