### ISSUE TITLE
[Device Support Request] TS0601 by _TZE200_bq5c8xfe (Temperature And Humidity Sensor)

### ISSUE THREAD

**Issue by brian-kehoe** [zigpy/zha-device-handlers#937]
**Is your feature request related to a problem? Please describe.**
I can connect it to ZHA, it generates a device listing but no entities.
It is a Temperature And Humidity Sensor
Is it possible to integrate it?

[https://www.aliexpress.com/item/1005002281706726.html](https://www.aliexpress.com/item/1005002281706726.html)

![image](https://user-images.githubusercontent.com/67521011/123240531-4aecf600-d4d8-11eb-9b6e-508a0f98cf63.png)

**Describe the solution you'd like**
I would like to be able to see the Temperature And Humidity values

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
`{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0, *allocate_address=True, *complex_descriptor_available=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False, *is_valid=True, *logical_type=<LogicalType.EndDevice: 2>, *user_descriptor_available=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_bq5c8xfe",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}`

**Additional context**
Version
supervisor-2021.06.3

****Debug Logs**
New device 0xc6a7 (84:71:27:ff:fe:09:61:61) joined the network
[0xc6a7] Scheduling initialization
Received frame on uninitialized device <Device model=None manuf=None nwk=0xC6A7 ieee=84:71:27:ff:fe:09:61:61 is_initialized=False> from ep 0 to ep 0, cluster ZDOCmd.Device_annce: b'\xFF\xA7\xC6\x61\x61\x09\xFE\xFF\x27\x71\x84\x80'
[0xc6a7:zdo] ZDO request ZDOCmd.Device_annce: [0xC6A7, 84:71:27:ff:fe:09:61:61, 128]
Tries remaining: 3
[0xc6a7] Requesting 'Node Descriptor'
Tries remaining: 2
[0xc6a7] Extending timeout for 0x1d request
Received frame on uninitialized device <Device model=None manuf=None nwk=0xC6A7 ieee=84:71:27:ff:fe:09:61:61 is_initialized=False> from ep 0 to ep 0, cluster ZDOCmd.Node_Desc_rsp: b'\x1D\x00\xA7\xC6\x02\x40\x80\x02\x10\x52\x52\x00\x00\x2C\x52\x00\x00'
[0xc6a7] Got Node Descriptor: NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)
[0xc6a7] Discovering endpoints
Tries remaining: 3
[0xc6a7] Extending timeout for 0x1e request
Received frame on uninitialized device <Device model=None manuf=None nwk=0xC6A7 ieee=84:71:27:ff:fe:09:61:61 is_initialized=False> from ep 0 to ep 0, cluster ZDOCmd.Active_EP_rsp: b'\x1E\x00\xA7\xC6\x01\x01'
[0xc6a7] Discovered endpoints: [1]
[0xc6a7] Initializing endpoints [<Endpoint id=1 in=[] out=[] status=<Status.NEW: 0>>]
[0xc6a7:1] Discovering endpoint information
Tries remaining: 3
[0xc6a7] Extending timeout for 0x21 request
Received frame on uninitialized device <Device model=None manuf=None nwk=0xC6A7 ieee=84:71:27:ff:fe:09:61:61 is_initialized=False> from ep 1 to ep 1, cluster 0: b'\x08\x6C\x0A\x01\x00\x20\x46\xE2\xFF\x20\x1F\xE4\xFF\x20\x00'
Ignoring message (b'086c0a01002046e2ff201fe4ff2000') on cluster 0: unknown endpoint or cluster id: 'No cluster ID 0x0000 on (84:71:27:ff:fe:09:61:61, 1)'
Received frame on uninitialized device <Device model=None manuf=None nwk=0xC6A7 ieee=84:71:27:ff:fe:09:61:61 is_initialized=False> from ep 0 to ep 0, cluster ZDOCmd.Simple_Desc_rsp: b'\x21\x00\xA7\xC6\x14\x01\x04\x01\x51\x00\x01\x04\x00\x00\x04\x00\x05\x00\x00\xEF\x02\x19\x00\x0A\x00'
[0xc6a7:1] Discovered endpoint information: SizePrefixedSimpleDescriptor(endpoint=1, profile=260, device_type=81, device_version=1, input_clusters=[0, 4, 5, 61184], output_clusters=[25, 10])
Unknown cluster 61184
[0xc6a7] Extending timeout for 0x24 request
[0xc6a7:1:0x000a] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=False disable_default_response=False> manufacturer=None tsn=109 command_id=Command.Read_Attributes>
[0xc6a7:1:0x000a] ZCL request 0x0000: [[7]]
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=110 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00e\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=111 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00f\x02\x02\x00\x04\x00\x00\x00F'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=112 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00g\x03\x04\x00\x01\x02'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=113 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00h\x04\x02\x00\x04\x00\x00\x00F'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=36 command_id=Command.Read_Attributes_rsp>
[0xc6a7] Read model 'TS0601' and manufacturer '_TZE200_bq5c8xfe' from <Endpoint id=1 in=[basic:0x0000, groups:0x0004, scenes:0x0005, None:0xEF00] out=[ota:0x0019, time:0x000A] status=<Status.ZDO_INIT: 1>>
[0xc6a7] Discovered basic device information for <Device model='TS0601' manuf='_TZE200_bq5c8xfe' nwk=0xC6A7 ieee=84:71:27:ff:fe:09:61:61 is_initialized=True>
Device is initialized <Device model='TS0601' manuf='_TZE200_bq5c8xfe' nwk=0xC6A7 ieee=84:71:27:ff:fe:09:61:61 is_initialized=True>
Checking quirks for _TZE200_bq5c8xfe TS0601 (84:71:27:ff:fe:09:61:61)
Considering <class 'zhaquirks.xbee.xbee_io.XBeeSensor'>
Fail because endpoint list mismatch: {232, 230} {1}
Considering <class 'zhaquirks.xbee.xbee3_io.XBee3Sensor'>
Fail because endpoint list mismatch: {232, 230} {1}
Considering <class 'zhaquirks.smartthings.tag_v4.SmartThingsTagV4'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.smartthings.multi.SmartthingsMultiPurposeSensor'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.netvox.z308e3ed.Z308E3ED'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.gledopto.soposhgu10.SoposhGU10'>
Fail because endpoint list mismatch: {11, 13} {1}
Considering <class 'bellows.zigbee.application.EZSPCoordinator'>
Fail because device_type mismatch on at least one endpoint
device - 0xC6A7:84:71:27:ff:fe:09:61:61 entering async_device_initialized - is_new_join: True
device - 0xC6A7:84:71:27:ff:fe:09:61:61 has joined the ZHA zigbee network
[0xC6A7](TS0601): started configuration
[0xC6A7:ZDO](TS0601): 'async_configure' stage succeeded
[0xC6A7:1:0x0000]: finished channel configuration
[0xC6A7:1:0x0019]: finished channel configuration
Error handling '_save_attribute' event with (84:71:27:ff:fe:09:61:61, 1, 0, 4, '_TZE200_bq5c8xfe') params: FOREIGN KEY constraint failed
[0xC6A7:1:0x0000]: 'async_configure' stage succeeded
[0xC6A7:1:0x0019]: 'async_configure' stage succeeded
Error handling '_save_attribute' event with (84:71:27:ff:fe:09:61:61, 1, 0, 5, 'TS0601') params: FOREIGN KEY constraint failed
[0xC6A7](TS0601): completed configuration
[0xC6A7](TS0601): stored in registry: ZhaDeviceEntry(name='_TZE200_bq5c8xfe TS0601', ieee='84:71:27:ff:fe:09:61:61', last_seen=1634562221.9090862)
[0xC6A7](TS0601): started initialization
[0xC6A7:ZDO](TS0601): 'async_initialize' stage succeeded
[0xC6A7:1:0x0000]: initializing channel: from_cache: False
[0xC6A7:1:0x0000]: finished channel configuration
[0xC6A7:1:0x0019]: initializing channel: from_cache: False
[0xC6A7:1:0x0019]: finished channel configuration
[0xC6A7:1:0x0000]: 'async_initialize' stage succeeded
[0xC6A7:1:0x0019]: 'async_initialize' stage succeeded
[0xC6A7](TS0601): power source: Battery or Unknown
[0xC6A7](TS0601): completed initialization
None: polling current state
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=114 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00i\x03\x04\x00\x01\x02'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=115 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00j\x04\x02\x00\x04\x00\x00\x002'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=116 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00k\x01\x02\x00\x04\x00\x00\x00\xd8'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=117 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00l\x02\x02\x00\x04\x00\x00\x00F'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=118 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00m\x03\x04\x00\x01\x02'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=119 command_id=1>
[0xc6a7:1:0xef00] Unknown cluster-specific command 1
[0xc6a7:1:0xef00] ZCL request 0x0001: b'\x00n\x04\x02\x00\x04\x00\x00\x002'
[0xc6a7:1:0xef00] No handler for cluster command 1
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=120 command_id=36>
[0xc6a7:1:0xef00] Unknown cluster-specific command 36
[0xc6a7:1:0xef00] ZCL request 0x0024: b'\x00\x1b'
[0xc6a7:1:0xef00] No handler for cluster command 36
[0xc6a7:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=121 command_id=17>
[0xc6a7:1:0xef00] Unknown cluster-specific command 17
[0xc6a7:1:0xef00] ZCL request 0x0011: b'\x00\x1c@'
[0xc6a7:1:0xef00] No handler for cluster command 17

**Comment by rampachuflo** [comment]
Hello
I'm interested too
Did you solved it? thank you

**Comment by brian-kehoe** [comment]
> Hello I'm interested too Did you solved it? thank you

No, there has been no update on this issue since I logged it. I have added the Debug logs to see if that will help resolve the issue.

**Comment by jacekk015** [comment]
@brian-kehoe Still interested? We can try do make it supported device.

**Comment by brian-kehoe** [comment]
Yes, definitely still interested in helping to get this working

**Comment by jacekk015** [comment]
@MattWestb Where to we put it and how do we name it in your Matrix??
https://github.com/zigpy/zigpy/discussions/653#discussioncomment-314395

**Comment by MattWestb** [comment]
The tuya TRV matrix is being very large and as discussion it only i that can ding changes.
I thinking doing one Wiki with tuya DP devices and subcategories and liking to smaller discussions for not getting them too large and not possible reading thm for user.
Also its possible changing  the link in the wiki to one new page if the old is not wanted.

**Comment by MattWestb** [comment]
Ops i have making one more generell matrix for Zigbee and DP devices but its not up to date.
I can braking it in one Zigbee nad one DP for getting it working better.
https://github.com/zigpy/zigpy/wiki/tuya-Matrix

**Comment by jacekk015** [comment]
@brian-kehoe 
Enable DEBUG logging in configuration.yaml
```
logger:
  default: info
  logs:
    homeassistant.components.zha: debug
    zigpy: debug
    zhaquirks: debug
```
Enable custom quirk option and put that file into that folder[create it if don't exists].
[ts0601_sensor.py.zip](https://github.com/zigpy/zha-device-handlers/files/7644731/ts0601_sensor.py.zip)
```
zha:
  custom_quirks_path: /config/zha_custom_quirks/
```

Restart HA!, remove device from HA, pair it, wait about 5 minutes and paste here ALL the logs from HA logs.
If it's big put it here as a file or use pastebin.com
Do NOT cut anything from the logs.
There will be no fireworks now, but device will present us in the logs all data it sends.

**Comment by MattWestb** [comment]
Short answer for the original question:
i thing `ts0601_temperature.py`  or  `ts0601_temp.py` is OK and if its having extra humidity or light it can going in the same.

**Comment by brian-kehoe** [comment]
> @brian-kehoe Enable DEBUG logging in configuration.yaml
> 
> ```
> logger:
>   default: info
>   logs:
>     homeassistant.components.zha: debug
>     zigpy: debug
>     zhaquirks: debug
> ```
> 
> Enable custom quirk option and put that file into that folder[create it if don't exists][unzip it ;-)] [ts0601_sensor.py.zip](https://github.com/zigpy/zha-device-handlers/files/7644731/ts0601_sensor.py.zip)
> 
> ```
> zha:
>   custom_quirks_path: /config/zha_custom_quirks/
> ```
> 
> Restart HA!, remove device from HA, pair it, wait about 5 minutes and paste here ALL the logs from HA logs. If it's big put it here as a file or use pastebin.com Do NOT cut anything from the logs. There will be no fireworks now, but device will present us in the logs all data it sends.
[Log file 03122021.txt](https://github.com/zigpy/zha-device-handlers/files/7647817/Log.file.03122021.txt)

I have attached the log file here

**Comment by jacekk015** [comment]
@brian-kehoe Here's first dev version.
Check what's working, what's not.
After you put the file into the "zha_custom_quirks" folder restart is needed!
[ts0601_temperature.py.zip](https://github.com/zigpy/zha-device-handlers/files/7649357/ts0601_temperature.py.zip)

Your device shows battery level under attribute 0x0204, and log says it's value is 40.
Original Tuya code makes from it 80% probably.
If you could put a new pack of batteries and work a bit with that 5-10 minutes, and put here logs.
We will see which value is sent for 100% new batteries. I'm not even sure if that remaining percentage or level.

 
I've seen in Z2M and in your logs one parameter that we don't know what it is.
It's under attribute 0x0403 - and your logs shows a value [1] there.
Do you have some settings option on your device?? Maybe battery low alarm or something??
There's need to be some action that changes 0x0403 from [1] to [0] - we could code it, but we need to know what it is.
Maybe you used it with original Tuya app and know what it is?
```
2021-12-03 08:05:10 DEBUG (MainThread) [zigpy.zcl] [0x2be0:1:0xef00] ZCL request 0x0001: [Command(status=0, tsn=232, command_id=1027, function=0, data=[1, 1])]
2021-12-03 08:05:10 DEBUG (MainThread) [zhaquirks.tuya] [0x2be0:1:0xef00] Received value [1] for attribute 0x0403 (command 0x0001)
```

**Comment by brian-kehoe** [comment]
When I place ts0601_temperature.py into the \config\custom_zha_quirks folder it seems to do something to the ZHA integration

Logger: homeassistant.config_entries
Source: deps/lib/python3.9/site-packages/zhaquirks/tuya/__init__.py:665
First occurred: 14:03:18 (1 occurrences)
Last logged: 14:03:18

Error setting up entry TI CC2531 USB CDC, s/n: __0X00124B001CCC7BB0 - Texas Instruments for zha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 102, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 152, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/usr/local/lib/python3.9/site-packages/zigpy/application.py", line 61, in new
    await app._load_db()
  File "/usr/local/lib/python3.9/site-packages/zigpy/application.py", line 53, in _load_db
    await self._dblistener.load()
  File "/usr/local/lib/python3.9/site-packages/zigpy/appdb.py", line 383, in load
    device = zigpy.quirks.get_device(device)
  File "/usr/local/lib/python3.9/site-packages/zigpy/quirks/__init__.py", line 44, in get_device
    return _DEVICE_REGISTRY.get_device(device)
  File "/usr/local/lib/python3.9/site-packages/zigpy/quirks/registry.py", line 148, in get_device
    device = candidate(device._application, device.ieee, device.nwk, device)
  File "/usr/local/lib/python3.9/site-packages/zigpy/quirks/__init__.py", line 98, in __init__
    self.add_endpoint(endpoint_id, replace_device=replaces)
  File "/usr/local/lib/python3.9/site-packages/zigpy/quirks/__init__.py", line 113, in add_endpoint
    ep = custom_ep_type(self, endpoint_id, replacement_data, replace_device)
  File "/usr/local/lib/python3.9/site-packages/zigpy/quirks/__init__.py", line 137, in __init__
    cluster = c(self, is_server=True)
  File "/config/deps/lib/python3.9/site-packages/zhaquirks/tuya/__init__.py", line 665, in __init__
    self.endpoint.device.battery_bus.add_listener(self)
AttributeError: 'TuyaSensor' object has no attribute 'battery_bus'

**Comment by brian-kehoe** [comment]
Thanks, I have added two new log files
1) New .py file and old batteries
2) Remove device, install new batteries and re-add

[Log file 08122021 - Old Batteries.txt](https://github.com/zigpy/zha-device-handlers/files/7677094/Log.file.08122021.-.Old.Batteries.txt)
[Log file 08122021 - Remove Readd and New Batteries.txt](https://github.com/zigpy/zha-device-handlers/files/7677095/Log.file.08122021.-.Remove.Readd.and.New.Batteries.txt)

**Comment by jacekk015** [comment]
@brian-kehoe You didn't wrote most important thing.
Does it work???
I see 19,1 degrees, 48% humidity and 100% battery level

I also see still unknown attribute 0x0403 with value [2]
```
2021-12-08 15:32:46 DEBUG (MainThread) [zhaquirks.tuya] [0x19e1:1:0xef00] Received value [2] for attribute 0x0403 (command 0x0001)
```

**Comment by brian-kehoe** [comment]
Oh, I didn't know it was returning data to the logs because on the front end it is just displaying "Unknown" for the Temperature, Humidity and Power values

![image](https://user-images.githubusercontent.com/67521011/145251671-dcfd8090-faeb-4c4b-92d2-f912131a04b5.png)

**Comment by jacekk015** [comment]
@brian-kehoe 
Used new approach for this code, made some correction now.
But I'm surprised that battery level didn't work properly - it should with this code.
Replace file and restart HA
[ts0601_temperature.py.zip](https://github.com/zigpy/zha-device-handlers/files/7677887/ts0601_temperature.py.zip)

**Comment by brian-kehoe** [comment]
Seeing some odd behaviour. I removed, restarted and re-added a few times

Attempt 1
![image](https://user-images.githubusercontent.com/67521011/145264625-ba0a16cc-e49f-4daa-abfb-a8e7d1fd2d42.png)

Attempt 2
![image](https://user-images.githubusercontent.com/67521011/145264642-bf70fa16-ef9f-4d51-8b3f-eecfbcddf701.png)


[Log file 08122021 - New File.txt](https://github.com/zigpy/zha-device-handlers/files/7678134/Log.file.08122021.-.New.File.txt)

**Comment by jacekk015** [comment]
@brian-kehoe You have some strange problems in communication:
```
2021-12-08 18:33:31 DEBUG (MainThread) [zigpy.zcl] [0x6752:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=116 command_id=1>
2021-12-08 18:33:31 DEBUG (MainThread) [zigpy.zcl] [0x6752:1:0xef00] ZCL request 0x0001: [Command(status=0, tsn=91, command_id=516, function=0, data=[4, 0, 0, 0, 100])]
2021-12-08 18:33:31 DEBUG (MainThread) [zhaquirks.tuya] [0x6752:1:0xef00] Received value [0, 0, 0, 100] for attribute 0x0204 (command 0x0001)
2021-12-08 18:33:31 DEBUG (MainThread) [zigpy_znp.zigbee.application] Max concurrency reached, delaying requests (10 enqueued)
```
**Max concurrency reached, delaying requests (10 enqueued)**
It started to show when you've put new batteries.


Here corrected file - try it now:
[ts0601_temperature.py.zip](https://github.com/zigpy/zha-device-handlers/files/7684613/ts0601_temperature.py.zip)

**Comment by brian-kehoe** [comment]
New file applied, restarted, removed and readded device

The device does not appear to have any entities

![image](https://user-images.githubusercontent.com/67521011/145401072-685b909f-a912-4675-a90b-471206c12fff.png)

[Log file 09122021.txt](https://github.com/zigpy/zha-device-handlers/files/7685237/Log.file.09122021.txt)

**Comment by jacekk015** [comment]
@brian-kehoe You have some Zigbee problems with communication. That device wasn't properly initialized.
You've got plenty of errors in the log.
Other devices are also dropping on communication:
```
2021-12-09 12:54:34 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0x7C47:1:0x0008]: failed to get attributes '['current_level']' on 'level' cluster: Request failed after 5 attempts: <Status.MAC_NO_ACK: 233>
```
